# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'nubank' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for nubank

  target 'nubank-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'nubankTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
